# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false
  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: '%env(REDIS_URL)%'
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  
  esi: true
  #fragments: true
  php_errors:
    log: true

when@prod:
  framework:
    http_cache: true

when@dev:
  framework:
    http_cache: true
when@test:
  framework:
    test: true
    http_cache: true
    session:
      storage_factory_id: session.storage.factory.mock_file
