parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $akismetkey: '%env(AKISMET_KEY)%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\Utils\HttpClientInterface: '@App\Service\Utils\HttpClientUtils'
  App\EventListener\ConferenceEntityListener:
    tags:
      - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Conference' }
      - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Conference' }